name: Super-Linter

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - development
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Super-Linter with adjusted rules
        uses: super-linter/super-linter@v7.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_PYTHON_PYLINT: false  # Disables Pylint strict rules
          VALIDATE_JSCPD: false  # Ignore duplicate code warnings
          VALIDATE_CHECKOV: false
          FIX_HTML_PRETTIER: true
          FIX_PYTHON_BLACK: true
          FIX_YAML_PRETTIER: true
