name: Super-Linter and Deploy

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - development
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Super-Linter
        uses: super-linter/super-linter@v7.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_JSCPD: false
          VALIDATE_CHECKOV: false
          FIX_HTML_PRETTIER: true
          FIX_PYTHON_BLACK: true
          FIX_YAML_PRETTIER: true

  js_cpd_check:
    name: Check for Duplicate Code (JSCPD)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run JSCPD with custom ignore settings
        run: npx jscpd --config .jscpd.json --ignore "**/.github/workflows/**"

  deploy_lambda:
    name: Deploy Lambda Functions
    runs-on: ubuntu-latest
    needs: lint
    if: github.ref == 'refs/heads/development'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Lambda Functions
        run: |
          for dir in lambda/*; do
            if [ -d "$dir" ]; then
              FUNCTION_NAME=$(basename "$dir")
              zip -r "$FUNCTION_NAME.zip" "$dir"
              aws lambda update-function-code --function-name "$FUNCTION_NAME" --zip-file "fileb://$FUNCTION_NAME.zip"
              rm "$FUNCTION_NAME.zip"
            fi
          done

  deploy_s3:
    name: Deploy index.html to S3
    runs-on: ubuntu-latest
    needs: lint
    if: github.ref == 'refs/heads/development' && contains(github.event.head_commit.message, 'index.html')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync index.html to S3
        run: |
          aws s3 sync ./web/ s3://your-bucket-name --exclude "*" --include "index.html" --delete
