name: Super-Linter

on:
  pull_request:
    branches:
      - main
      - development  # Add the development branch here
    types: [opened, reopened]  # Trigger linting on PR open or reopen

permissions:
  contents: read
  packages: read
  statuses: write  # For GitHub Actions status checks

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full git history for linting

      - name: Run Super-Linter
        uses: super-linter/super-linter@v7.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_CHECKOV: false
          FIX_HTML_PRETTIER: true
          FIX_PYTHON_BLACK: true
          FIX_YAML_PRETTIER: true
