name: Super-Linter and Deploy

on:
  push:
    branches:
      - development  # Trigger on pushes to the development branch
      - main          # Optional: Trigger on pushes to the main branch as well
  pull_request:
    branches:
      - development  # Trigger on pull requests to the development branch
    types: [opened, reopened, synchronize]  # Trigger when PR is opened, reopened, or synchronized with new commits

permissions:
  contents: read
  packages: read
  statuses: write  # To report GitHub Actions status checks

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full git history for accurate comparison

      - name: Run Super-Linter
        uses: super-linter/super-linter@v7.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_CHECKOV: false
          FIX_HTML_PRETTIER: true
          FIX_PYTHON_BLACK: true
          FIX_YAML_PRETTIER: true

  deploy_lambda:
    name: Deploy Lambda Functions
    runs-on: ubuntu-latest
    needs: lint  # This ensures the lint job runs first
    if: github.ref == 'refs/heads/development'  # Only deploy on push to development branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2  # ✅ Updated to the latest version
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Replace with your region

      - name: Deploy Lambda Functions
        run: |
          for dir in lambda/*; do
            if [ -d "$dir" ]; then
              FUNCTION_NAME=$(basename "$dir")
              zip -r "$FUNCTION_NAME.zip" "$dir"
              aws lambda update-function-code --function-name "$FUNCTION_NAME" --zip-file "fileb://$FUNCTION_NAME.zip"
              rm "$FUNCTION_NAME.zip"
            fi
          done

  deploy_s3:
    name: Deploy index.html to S3
    runs-on: ubuntu-latest
    needs: lint  # Ensure lint job runs first
    if: github.ref == 'refs/heads/development' && contains(github.event.head_commit.message, 'index.html')  # Only deploy if index.html is updated

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2  # ✅ Updated to the latest version
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Replace with your region

      - name: Sync index.html to S3
        run: |
          aws s3 sync ./web/ s3://your-bucket-name --exclude "*" --include "index.html" --delete
