name: Deploy Web App to S3

on:
  push:
    branches:
      - 'main'
    paths:
      - 'index.html'  # Only trigger when index.html is updated

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Upload index.html to S3
        run: |
          aws s3 cp "index.html" "s3://s3-final-upload-akeem-williams-2025-04-23/index.html" --content-type "text/html"
